#cloud-config
 runcmd:
   - touch /tmp/test.txt
   - sudo yum -y install httpd
   - sudo systemctl enable httpd
   - sudo service httpd start
   - sudo chkconfig httpd on
   - sudo touch /var/www/html/index.html
   - sudo chmod ugo+w /var/www/html/index.html
   - sudo echo 'Hello, World' > /var/www/html/index.html
